language: c


before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-arm-none-eabi --force-yes
  # Print versions we use
  - arm-none-eabi-gcc --version
  
install:
  - mkdir -p webroot
  - mkdir -p repos

script:
- ./update_browserhax_auto_static.sh $TRAVIS_BUILD_DIR/repos $TRAVIS_BUILD_DIR/webroot ""

before_deploy:
- cp -pf generateqrcode.php webroot/
- export RELEASE_FILENAME=webroot-$TRAVIS_TAG
- tar -czf $RELEASE_FILENAME.tar.gz webroot/


deploy:
  provider: releases
  api_key:
    secure: S7SLgiRQdwvnS0H6vdmhpiPCXDmeKHJEP2P/LmeGDtjjyIZWgHypKcc6dbIhGth+Lhj+AZ2ln293xaty84tELSb8xVzYDxpNhQulimecnAD5MMHENn0e88y2caTmYUnDWEgZ8t3zWq56qs62dh56Jlvx8bTMrQ3OgoIqQ/QM76AAMpqXGBIUIFPD+YP6UfuVl42PjtTuA01g3NFEbEI7iiMe8SBYmgz0Wicb72aXE3QTa8C6llZhY7/Av/khou5+gR86WyTPhBXj82GH7DFybrl6QAyJyQIYbYO9cwPp8P6yL6J0ivusLW/M+2nUgIAW6/Fv6fH+efv0pyJsMr4fsQUGtPNKoYvjE6t1iLtBUNBNgHZa3KAOY3DVFkQdm25kF2OMp5ux6K++cT+SeYcgULB3CVukvtQo3wp4nGvXLxOZLRY4IFfbPnbxA/M2JeptdkOdX7xzoO4VajCxyTGAR42M174KRKrtzQ8fEJqZZSIzz+wnomPhdxMBA/eQMI8Pn6t4hrkBRNTfinxmvtixTCzCSoJyuF98eF0KUC5ow1dL0lRasZKQzYJm6x64Iw/gTJmh/pnFCwuHYyWQUMeYjFRH+nqbftGK88CxAh5SO8xs5/xKiTwli18ZAVhIW0ni/EqRelkjBUBxoPPzK9i1gcN4bYtS+AxIKMn6BVzQZO8=
  file:
    - $RELEASE_FILENAME.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: Cartman123/update_browserhax